export type PlantRow = {
  id: string;
  nickname: string;
  species?: string | null;
  water_every?: string | null;
  fert_every?: string | null;
  last_watered_at?: string | null;
  last_fertilized_at?: string | null;
};

const NAMES = [
  "Peruvian Old Man Cactus",
  "Red-Headed Irishman",
  "Golden Barrel Cactus",
  "Pothos",
  "Begonia",
  "Azalea",
  "Hydrangea",
  "Clematis",
  "Gaillardia",
  "Black-eyed Susan",
  "Sunkiss",
  "African Marigold",
  "Geraniums",
  "Gladiolus",
  "Snapdragons",
  "Primrose",
  "Tobacco",
  "Phlox",
  "Yarrow",
  "Zinnia",
  "Sunflower",
  "Hollyhock",
  "Chinese Money Plant",
  "Christmas Cactus",
  "Bunny Ear Cactus White",
  "Aloe Vera",
  "Lime Tree",
  "Jade Plant",
  "ZZ Plant",
  "Bunny Ear Cactus",
  "Blue Torch Column Cactus",
  "Fiddle Leaf Fig Tree",
  "India Rubber Plant",
  "Coffee big",
  "Croton",
  "Chinese money plant",
  "Coffee Mini",
  "Elephant Ears",
  "Emory's Barrel Cactus",
  "Spinystar",
  "Golden Pothos",
  "Heart of Jesus",
  "Hilo Beauty",
  "Kishu Mandarin",
  "Mammillaria Disco",
  "Mini Kordana Rose",
  "Monstera",
  "Neoraimondia herzogiana",
  "Peace Lily",
  "Persian Shield",
  "Birkin",
  "Pink Princess Philodendron",
  "Rattlesnake Plant",
  "Rex Begonia Prop",
  "Snake Plant",
  "Snake Plant Norma",
  "Tuberous Begonia",
  "ZZ Prop",
  "Maranta Prayer Plant",
  "Burgundy Rubber Tree",
  "Strawberries",
  "Basil",
  "Lettuce",
  "Lotus",
  "McJesus",
  "Mr Moody",
  "Coffea arabica",
  "Hibiscus",
  "Lily",
  "Venus Fly Trap",
  "Bleeding Heart",
  "Shasta Daisy",
  "Delphinium",
  "Icelandic Poppy",
  "Foxglove",
  "Periwinkle",
  "Wandering Jew",
  "Bee Balm",
  "Astilbe",
  "Lupine",
  "Blazingstar",
  "Strawflower",
  "Lil Fiddle",
];

export const fallbackPlants: PlantRow[] = NAMES.map((name, i) => ({
  id: String(i + 1),
  nickname: name,
  species: name,
}));


export function getFallbackPlant(id: string): PlantRow | null {
  return fallbackPlants.find((p) => p.id === id) ?? null;
}
